### PR TITLE
Issue #24 - Added "components" function to CLI

### PR DESCRIPTION
**Pull request by RusinR**
A few additional features that may need to be tweaked or removed per maintainer discretion:

1. If it cannot find the "app/meld/components" or "app/templates/meld" folders, it will return and print "Failed, could not find xyz directories"
2. Contains a basic "toggle" example, rather than a non-functional shell
3. Will attempt to change the component name to an uppercase for the class name (`class Example(Component):`). 
It is possible that a user has done their own capitalization (ExampleComponent), so it does not use .capitalize() to avoid forcing lowercase for the rest of the string

### CODE REVIEW

**Comment by mikeabrahamsen** [comment]
This is going to be awesome. Can we add some feedback for the user if we run into an `OSError`, as opposed to failing silently?
Also, what do you think it would take to create a new component no matter what directory the user is in? Maybe we can find the root directory of the project somehow?

**Comment by RusinR** [comment]
### **Can we add some feedback for the user if we run into an OSError, as opposed to failing silently?**
Of course! I copied the structure from "new" so I'll have to check if it's better to get specific with the exceptions, or leave it as OSError and print a more generalized statement.
### **Also, what do you think it would take to create a new component no matter what directory the user is in?**
It would be impossible if you're outside the project directory, like after running "meld new", unless we cache the most recently built project (could get messy).
However, I could add some basic detections for folder structure and attempt to find the root if you ARE inside the project directory, but not at root.

I look into both of these on the evening of the 19th, EST.

**Comment by mikeabrahamsen** [comment]
Let's not worry about being able to add a component from any directory at the moment. Your solution of being in the project root will work great for now. We just need to make sure we have appropriate errors and documentation in place.

**Comment by RusinR** [comment]
This should be good, let me know what you think!

**Review by mikeabrahamsen — APPROVED** [review]
Thank you for this! I can't wait to start using it

**Pull request merged**
